### ISSUE TITLE
Cannot perform operation. Too complex, sorry

### ISSUE THREAD

**Issue by tinder-yisongwu** [nvinayshetty/StateArts#2] opened 2019-04-08 20:41 UTC
I tried to use the plugin in android studio but get a `Cannot perform operation. Too complex, sorry` error.

**Comment by nvinayshetty** [comment] 2019-04-09 02:12
Do you have graph-viz installed? Which OS you are using?

**Comment by tinder-yisongwu** [comment] 2019-04-09 20:58
Yeah I do have that installed on the Mac OS 10.13.5

**Comment by nvinayshetty** [comment] 2019-04-10 03:21
Do you see a red error icon in the bottom right corner of the IDE when this error happens? If yes it will have some stack trace could you share that stack trace?
Is the dot file generated correctly? it's on build/stateArt/state folder.

**Comment by nvinayshetty** [comment] 2019-04-18 06:47
@tinder-yisongwu Any updates? Can I close this issue?

**Comment by nvinayshetty** [comment] 2019-04-25 03:15
Closing as I'm not able to reproduce.

**Closed as completed by nvinayshetty** 2019-04-25 03:15 UTC

**Comment by rrozek** [comment] 2019-05-27 15:01
in my case the issue was by default under windows graphviz installs under 
```C:\Program Files (x86)\Graphviz2.38```
, while plugin search for 
```C:\Program Files (x86)\Graphviz 2.38```
(note the space) when i added space in my pathfile then it worked. @tinder-yisongwu

**Comment by xoif** [comment] 2019-08-08 05:37
I'm struggling with the same issue under linux and Android Studio 3.4.2. 
Graphviz is installed in /usr/bin/dot and dot -V prints "graphviz version 2.38.0".
I would appreciate to see more telling error messages, as my state machine isn't really that complex...

**Comment by blipinsk** [comment] 2019-08-25 13:11
I have the same issue.

Graphs for some state machines are displayed when clicking the icon and some of them result in `Cannot perform operation. Too complex, sorry` message. 

`graphviz` installed with `brew` on Mac.

Can I provide any logs or something for you to debug the issue @nvinayshetty?

**Comment by blipinsk** [comment] 2019-08-25 13:39
I believe I found the issue, it was due to **code formatting**.

The plugin expects `transitionTo` methods to be formatted in a single line.

this is **ok** 👍 for the plugin:
```
transitionTo(SomeEvent.WhatALongName, SomeSideEffect.WhatALongName)
```


this is **very not ok** 👎for the plugin:
```
transitionTo(
    SomeEvent.WhatALongName, 
    SomeSideEffect.WhatALongName
)
```

**Comment by zjn0505** [comment] 2020-01-11 05:33
Same error here on mac with graphviz installed.
I can create state art for all other state machines in the project except one.
I didn't apply multi-line code format to transition.

Now even I copy this state machine to a new class, or comment out with only one state left, still got the error.
